name: proyecto_aguapluss
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6            # API REST
  provider: ^6.1.2         # manejo de estado
  fluttertoast: ^8.2.4     # mensajes flotantes
  syncfusion_flutter_datagrid: ^24.2.9   # tablas avanzadas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true